from PyQt5 import QtCore, QtGui, QtWidgets


class DeSettingsLayout(QtWidgets.QWidget):
    def __init__(self, parent, locale) -> None:
        super().__init__(parent)
        self.strings = locale
    
    def setupUi(self, settings_window):
        settings_window.setObjectName("settings_window")
        settings_window.resize(490, 331)
        settings_window.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.gridLayoutWidget = QtWidgets.QWidget(settings_window)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 491, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.general = QtWidgets.QWidget()
        self.general.setObjectName("general")
        self.label = QtWidgets.QLabel(self.general)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.general)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 141, 22))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.tabWidget.addTab(self.general, "")
        self.about = QtWidgets.QWidget()
        self.about.setObjectName("about")
        self.label_3 = QtWidgets.QLabel(self.about)
        self.label_3.setGeometry(QtCore.QRect(190, 160, 89, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.about)
        self.label_2.setGeometry(QtCore.QRect(160, 10, 150, 150))
        self.label_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.about)
        self.label_4.setGeometry(QtCore.QRect(190, 200, 91, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.about)
        self.label_5.setGeometry(QtCore.QRect(170, 230, 131, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.about, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.save_button = QtWidgets.QPushButton(settings_window)
        self.save_button.setGeometry(QtCore.QRect(410, 305, 75, 23))
        self.save_button.setDefault(True)
        self.save_button.setObjectName("save_button")
        self.buttonGroup = QtWidgets.QButtonGroup(settings_window)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.save_button)
        self.cancel_button = QtWidgets.QPushButton(settings_window)
        self.cancel_button.setGeometry(QtCore.QRect(320, 305, 75, 23))
        self.cancel_button.setObjectName("cancel_button")
        self.buttonGroup.addButton(self.cancel_button)
        self.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        self.retranslateUi(settings_window)
        self.tabWidget.setCurrentIndex(1)

    def retranslateUi(self, settings_window):
        _translate = QtCore.QCoreApplication.translate
        settings_window.setWindowTitle(_translate("settings_window", "Settings"))
        self.label.setText(_translate("settings_window", "Language"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.general), _translate("settings_window", "General"))
        self.label_3.setText(_translate("settings_window", "**DeTuner**"))
        self.label_2.setText(_translate("settings_window", "TextLabel"))
        self.label_4.setText(_translate("settings_window", "Version"))
        self.label_5.setText(_translate("settings_window", "by broken_cursor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.about), _translate("settings_window", "About"))
        self.save_button.setText(_translate("settings_window", "Save"))
        self.cancel_button.setText(_translate("settings_window", "Cancel"))
