{
    "format": "detuner_locale",
    "version": "0.0.1",
    "locale": "en_US",
    "language": "English",
    "strings": {
        "main_window": {
            "menubar": {
                "file_menu": "File"
            },
            "actions": {
                "add_backup": "Add backup",
                "delete_backup": "Delete backup",
                "extract": "Extract",
                "exit": "Exit"
            },
            "buttons": {
                "add_backup": "Add backup",
                "extract": "Extract!"
            },
            "extraction_settings": {
                "extract": "**Extract:**",
                "call_history": "Call History",
                "calendar": "Calendar",
                "camera_roll": "Camera Roll",
                "contacts": "Contacts",
                "notes": "Notes",
                "sms_imessage": "SMS & iMessage",
                "voice_memos": "Voice Memos",
                "voicemail_messages": "Voicemail Messages"
            },
            "device_info": {
                "device_label": "SELECT BACKUP",
                "model": "Model:",
                "ios_version": "iOS Version:",
                "serial_number": "Serial Number",
                "IMEI": "IMEI"
            },
            "backup_info": {
                "backup_info": "**Backup Info**",
                "date": "Date:",
                "itunes_version": "iTunes version:",
                "encrypted": "Encrypted:",
                "passcode_set": "Passcode set:"
            },
            "status_tips": {
                "add_backup_button": "Import backup from non-iTunes directory",
                "backup_table": "Table of imported backups",
                "device_name_label": "User-specified device name",
                "device_image": "Device icon",
                "model_label": "Model name",
                "ios_version_label": "iOS version",
                "serial_number_label": "Serial Nubmer",
                "imei_label": "IMEI",
                "call_history_checkbox": "Extract call history?",
                "calendar_checkbox": "Extract calendar data?",
                "camera_roll_checkbox": "Extract Camera Roll?",
                "contacts_checkbox": "Extract contacts?",
                "notes_checkbox": "Extract notes?",
                "sms_checkbox": "Extract SMS & iMessage chat history?",
                "voice_memos_checkbox": "Extract Voice Memos?",
                "voicemail_checkbox": "Extract voicemail?",
                "start_button": "Start extraction",
                "backup_date_label": "Date of last backup",
                "backup_itunes_ver_label": "iTunes version used for backup",
                "backup_is_encrypted_label": "Was backup encrypted?",
                "backup_passcode_set_label": "Was passcode set?",
                "action_add_backup": "Import backup from non-iTunes directory",
                "action_export": "Start extraction",
                "action_exit": "Quit DeTuner"
            }
        },
        "quit_dialog": {
            "window_title": "Quit?",
            "label": "Quit DeTuner?",
            "quit_button": "Quit",
            "cancel_button": "Cancel"
        },
        "handler": {
            "backup_directory_prefix": "Backup_",
            "camera_roll_directory": "Camera Roll",
            "voice_memos_directory": "Voice Memos",
            "contacts_directory": "Contacts",
            "contacts_file_name": "Contacts",
            "call_history_directory": "Call History",
            "call_history_file_name": "Call History",
            "call_history_header": [
                "ID",
                "Phone Number",
                "Date",
                "Duration"
            ],
            "calendar_directory": "Calendar",
            "calendar_file_name": "Calendar",
            "calendar_event_template": "",
            "notes_directory": "Notes",
            "notes_note_template": "",
            "sms_imessage_directory": "SMS & iMessage",
            "sms_imessage_attachments_directory": "Attachments"
        }
    }
}